### ISSUE TITLE
Sorting Categories

### ISSUE THREAD

**Issue by Seaal** [Jackthehobbit/Jack.FoodTracker#14]
Do you want to be able to sort your own categories manually, or have them sorted alphabetically?

I think alphabetically makes sense for food, but I think it might be more intuitive to allow the person to change the order of categories? E.g.
- Meat
- Fish
- Vegetables
- Fruit
- Desserts
- Snacks

Rather than:
- Desserts
- Fish
- Fruit
- Meat
- Snacks
- Vegetables

**Comment by Jackthehobbit** [comment]
I agree. sorting catagories is a good idea but leave food alphabetical... just incase you havent already implemented this :+1:
